### PR TITLE
159 fix endpoint sql

### LINKED ISSUE #159: API endpoints aren't returning all data dump books
Many books in the OpenLibrary books dataset are missing genre and/or author data. Only books that have both author and genre data are being returned by the API's endpoints.

### PR DESCRIPTION
**Pull request by ElliotSchumacher**
This pull request correctly includes books that have missing author and/or genre information in search results and in requests for individual book details. It also specifies default response formats for authors and genres if no information is available. Finally, it includes demo and test data.

closes #159

### CODE REVIEW

File: back-end/app/controllers/book_controller.js [hunk 1]
```diff
@@ -51,7 +51,16 @@ exports.getMatchingBooks= async (info) => {
...
 	query += `;`;
     result = await db.query(query, params);
-	return result[0];
+    let data = result[0];
+    for (let index = 0; index < data.length; index++) {
+        let bookRecord = data[index];
+        if (bookRecord.authors) {
+            bookRecord.authors = bookRecord.authors.split(",");
+        } else {
+            bookRecord.authors = [];
```
Comment (nith2001) [inline back-end/app/controllers/book_controller.js:60]: Do you also need to run a genre check here like you did on LIne 97? I don't have experience with this so I'm just checking.

**Review by nith2001 — COMMENTED** [review]
Left a comment, looks pretty good to me other than the one genre check

File: back-end/app/controllers/book_controller.js (hunk 1 above)
Comment (ElliotSchumacher) [reply back-end/app/controllers/book_controller.js:60]: We don't only because we don't actually return any genre information to the front-end in the search endpoint which this method is for. The detail endpoint does return genre information and that is why line 97 does this thing for genres.

**Review by nith2001 — APPROVED** [review]
